language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t malmsteen8989/docker-react -f DockerFile.dev .

script:
    - docker run malmsteen8989/docker-react npm run test -- --coverage